-- Auto-generated by GenConformanceTests.lean — do not edit manually.

import Tests.Conformance.Generated.Builtin
import Tests.Conformance.Generated.Example
import Tests.Conformance.Generated.Term

-- Barrel for Tests.Conformance.Generated
