import Cryptograph.Ed25519.Field

namespace Cryptograph.Ed25519.Point

/-! ## Ed25519 Curve Points-/

open Cryptograph.Ed25519.Field

-- Edwards curve parameter d = -121665/121666 (mod p)
def d : Fp := -121665 / 121666

-- Point on Ed25519 curve in extended coordinates
structure EdPoint where
  x : Fp
  y : Fp
  z : Fp
  t : Fp

namespace EdPoint

-- Identity/neutral element (point at infinity)
def zero : EdPoint := ⟨0, 1, 1, 0⟩

-- Check if point is the identity
def isZero (p : EdPoint) : Bool :=
  p.x = 0 && p.y = p.z

-- Convert from affine coordinates (x, y)
def fromAffine (x y : Fp) : EdPoint :=
  ⟨x, y, 1, x * y⟩

-- Convert to affine coordinates (x, y)
def toAffine (p : EdPoint) : Fp × Fp :=
  let zinv := p.z⁻¹
  (p.x * zinv, p.y * zinv)

-- Point addition in extended coordinates
-- Based on the "add-2008-hwcd" formulas from EFD
def add (p q : EdPoint) : EdPoint :=
  let a := (p.y - p.x) * (q.y - q.x)
  let b := (p.y + p.x) * (q.y + q.x)
  let c := (p.t * q.t) * 2 * d
  let d := (p.z * q.z) * 2
  let e := b - a
  let f := d - c
  let g := d + c
  let h := b + a
  ⟨e * f, g * h, f * g, e * h⟩

instance : Add EdPoint := ⟨add⟩

-- Point doubling (optimized version of add(p, p))
-- Based on the "dbl-2008-hwcd" formulas from EFD
def double (p : EdPoint) : EdPoint :=
  let a := p.x^2
  let b := p.y^2
  let c := 2 * p.z^2
  let h := a + b
  let e := h - (p.x + p.y)^2
  let g := a - b
  let f := c + g
  ⟨e * f, g * h, f * g, e * h⟩

-- Scalar multiplication using double-and-add algorithm
-- More efficient than repeated addition
partial def scalarMul (n : Nat) (p : EdPoint) : EdPoint :=
  if n = 0 then zero
  else if n = 1 then p
  else
    let half := scalarMul (n / 2) p
    let doubled := double half
    if n % 2 = 0 then doubled else add doubled p

instance : HMul Nat EdPoint EdPoint := ⟨scalarMul⟩

-- Scalar multiplication from bytes (little-endian)
def scalarMulBytes (scalar : List UInt8) (p : EdPoint) : EdPoint :=
  let n := scalar.foldl (fun acc b => acc * 256 + b.toNat) 0
  scalarMul n p

instance : HMul (List UInt8) EdPoint EdPoint := ⟨scalarMulBytes⟩

-- Negate a point
def neg (p : EdPoint) : EdPoint :=
  ⟨-p.x, p.y, p.z, -p.t⟩

instance : Neg EdPoint := ⟨neg⟩

-- Ed25519 base point (generator)
-- x = 15112221349535400772501151409588531511454012693041857206046113283949847762202
-- y = 46316835694926478169428394003475163141307993866256225615783033603165251855960
def basePoint : EdPoint :=
  let x := Fp.ofNat 15112221349535400772501151409588531511454012693041857206046113283949847762202
  let y := Fp.ofNat 46316835694926478169428394003475163141307993866256225615783033603165251855960
  fromAffine x y

-- Decompress a point from y-coordinate and sign bit
-- Ed25519 uses point compression: only y and sign of x are stored
def decompress (yBytes : List UInt8) : Option EdPoint :=
  if yBytes.length ≠ 32 then none
  else do
    -- Extract sign bit from last byte
    let lastByte := yBytes[31]!
    let xSign := lastByte >>> 7

    -- Clear sign bit to get y coordinate
    let yBytes := yBytes.set 31 (lastByte &&& 0x7F)
    let y      ← Fp.fromBytesLE yBytes

    -- Recover x from y using curve equation: x^2 = (y^2 - 1) / (d*y^2 + 1)
    let yy := y^2
    let xx := (yy - 1) / ((d * yy) + 1)

    -- Compute square root (if exists)
    let x := xx ^ ((p + 3) / 8)

    -- Check if x^2 = xx
    if x^2 != xx then
      -- Try x * sqrt(-1) if x^2 ≠ xx
      -- For p ≡ 5 mod 8, sqrt(-1) = 2^((p-1)/4) mod p (NOT (-1)^((p-1)/4))
      let sqrt_m1 := (Fp.ofNat 2) ^ ((p - 1) / 4)
      let x       := x * sqrt_m1
      if x^2 != xx then none
      else
        -- Adjust sign of x
        let x := if (x.val % 2 == xSign.toNat) then x else -x
        some (fromAffine x y)
    else
      -- Adjust sign of x
      let x := if (x.val % 2 == xSign.toNat) then x else -x
      some (fromAffine x y)

-- Curve order (prime order of the subgroup generated by basePoint)
-- L = 2^252 + 27742317777372353535851937790883648493
def curveOrder : Nat := 2^252 + 27742317777372353535851937790883648493

-- Check if a point is in the prime-order subgroup.
-- A valid Ed25519 point lies on the curve, but the curve has cofactor h = 8,
-- so there are low-order points outside the prime-order subgroup.
-- A point P is in the subgroup iff L*P = identity.
def isInSubgroup (pt : EdPoint) : Bool := isZero (curveOrder * pt)

-- Compress a point to 32 bytes (y-coordinate + sign bit)
def compress (p : EdPoint) : List UInt8 :=
  let (x, y) := toAffine p
  let yBytes := Fp.toBytesLE y
  -- Set high bit of last byte to sign of x
  let lastByte := yBytes[31]!
  let xSign := if x.val % 2 = 0 then 0 else 0x80
  let yBytes := yBytes.set 31 (lastByte ||| xSign)
  yBytes

end EdPoint

end Cryptograph.Ed25519.Point
